VITE_SUPABASE_URL=https://knzwncgllcoyjoxwpicy.supabase.co
VITE_SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuenduY2dsbGNveWpveHdwaWN5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjYxNjE5MywiZXhwIjoyMDg4MTkyMTkzfQ.PWwn3OFuEtaSNeEmW3EhmY6TqK1lKb_LLlNV2G6n4RI
